[BUGFIX] Fix reflection on PHP 5.3.16
The fix for https://bugs.php.net/62715 landed in PHP 5.3.16, and because of
https://bugs.php.net/62874 reflection fails (in Production context) with a
pretty unhelpful exception:

 Fatal error: Uncaught exception … with message 'Parameter is not optional' in …

This change adds an additional check with isOptional() to the relevant code
part.

Change-Id: Ib7e763340f51fcd2d4f41291a4b8b80c33459d6b
Fixes: #40003
Releases: 1.1, 1.2
Original-Commit-Hash: 28c82ae23d90b17f6514b0cd93fae17dd7bc0dc7